### ISSUE TITLE
Next Pre-Release TODO

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/fastprop#6]
- [x] Fix the `'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.` warning
 - [x] Add the DOI to the printed citation request and a `CITATION.cff` to the repo

**Comment by JacksonBurns** [comment]
- [ ] remove the use of scikit learn scaler and imputers in favor of doing the work ourselves in native pytorch
